// Generated by CoffeeScript 1.11.1
var bgrect, dark_colors, gap_betw_cols, has_dark, height, hoffset, hscale, indent, index, max_length, n_per_col, pal, palettes, radius, svg, text, textwidth, vscale, vscaleL, vscaleR, width;

height = 400;

width = 800;

indent = 15;

textwidth = 115;

radius = 15;

gap_betw_cols = 30;

svg = d3.select("div#chart").append("svg").attr("height", height).attr("width", width);

bgrect = svg.append("rect").attr("x", 2).attr("y", 2).attr("height", height - 4).attr("width", width - 54).attr("fill", "white").attr("stroke", "black").attr("stroke-width", "3").on("click", function(d) {
  bgrect.attr("fill", "white");
  return text.attr("fill", "#333");
});

palettes = Object.keys(wes_palettes);

n_per_col = Math.ceil(palettes.length / 2);

vscaleL = d3.scalePoint().domain(d3.range(n_per_col)).range([0, height]).padding(1);

vscaleR = d3.scalePoint().domain(d3.range(n_per_col).map(function(d) {
  return d + n_per_col;
})).range([0, height]).padding(1);

vscale = function(d) {
  if (d < n_per_col) {
    return vscaleL(d);
  }
  return vscaleR(d);
};

hoffset = function(d) {
  if (d < n_per_col) {
    return indent;
  }
  return indent + width / 2 + gap_betw_cols / 2;
};

text = svg.selectAll("empty").data(palettes).enter().append("text").text(function(d) {
  return d;
}).attr("x", function(d, i) {
  return hoffset(i);
}).attr("y", function(d, i) {
  return vscale(i);
}).attr("fill", "#333");

max_length = d3.max(palettes.map(function(pal) {
  return wes_palettes[pal].length;
}));

hscale = d3.scalePoint().domain(d3.range(max_length)).range([textwidth, width / 2 - gap_betw_cols / 2]).padding(1);

dark_colors = {
  BottleRocket: [4, 5, 6],
  Cavalcanti: [1],
  Darjeeling2: [4],
  GrandBudapest: [2],
  Moonrise1: [3],
  Moonrise2: [3],
  Rushmore: [3]
};

has_dark = Object.keys(dark_colors);

for (index in palettes) {
  pal = palettes[index];
  svg.append("g").attr("id", pal).selectAll("empty").data(wes_palettes[pal]).enter().append("circle").attr("cy", vscale(index)).attr("cx", function(d, i) {
    return hoffset(index) + hscale(i);
  }).attr("r", radius).attr("fill", function(d) {
    return d;
  }).attr("class", function(d, i) {
    if (has_dark.indexOf(pal) >= 0 && dark_colors[pal].indexOf(i) >= 0) {
      return "dark";
    }
    return "light";
  }).on("click", function(d, i) {
    var f, this_class;
    bgrect.attr("fill", d);
    this_class = d3.select(this).attr("class");
    f = function() {
      if (this_class === "dark") {
        return "#ddd";
      }
      return "#333";
    };
    return text.attr("fill", f);
  });
}
